# name: Deploy WebGL

# on:
#   pull_request: {}
#   push: { branches: [main] }

# env:
#   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# jobs:
#   build:
#     name: Build project
#     runs-on: ubuntu-latest
#     steps:
#       # Checkout
#       - name: Checkout repository
#         uses: actions/checkout@v2
#         with:
#           lfs: true

#       # Cache
#       - uses: actions/cache@v1.1.0
#         with:
#           path: Library
#           key: Library

#       # Build
#       - name: Build project
#         uses: webbertakken/unity-builder@v2.0-alpha-1
#         with:
#           unityVersion: 2020.1.6f1
#           targetPlatform: WebGL



#       # Output
#       - uses: actions/upload-artifact@v1
#         with:
#           name: Build
#           path: build


name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2020.1.6f1
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_v2020.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2020.x.ulf
        
        # Activate unity
        - name: Activate Unity
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ./.github/Unity_v2020.x.ulf || exit 0
        
        # Build Windows and WebGL
        # - name: Build Windows Player
        #   run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildWindows64Player ./bin-win64/CISample.exe
        - name: Build WebGL Player
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod WebGLBuilder.build

        - name: Deploy project
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: builds/WebGLversion/ # The folder the action should deploy.
            CLEAN: true

        # - name: Archive Windows Build
        #   uses: actions/upload-artifact@v1
        #   with:
        #     name: CISampleWin64Binary
        #     path: ./bin-win64
        - name: Archive WebGL Build
          uses: actions/upload-artifact@v1
          with:
            name: CISampleWebGLBinary
            path: ./builds/WebGLversion
